name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:  

    runs-on: self-hosted

    steps:
   
      - name: Pull Docker Compose frontend image
        run: |
          docker-compose -f /home/ec2-user/deploy/docker-compose.yml pull frontend

      - name: Start frontend container in detached mode
        run: |
          docker-compose -f /home/ec2-user/deploy/docker-compose.yml up -d frontend

      - name: (Optional) Verify frontend container status (if needed)
        run: |
          docker ps | grep frontend  # Check if frontend container is running

